[metadata]
name = "chirp3d example"
version = "1.0.0"
identifier = "com.kraxarn.chirp3d_example"
creator = "kraxarn"
copyright = "Copyright (c) 2026 kraxarn"
url = "https://github.com/kraxarn/chirp3d"
type = "game"

[window]
title = "chirp3d example"
size = [1280, 720]
fullscreen = false
icon = ""

[run]
scene = "test"

[assets]
textures = []
models = ["scene", "blaster", "bullet"]
scripts = ["main"]

[input]
move_forward  = { keycode = ["w", "up"   ], axis    = "lefty",  deadzone = 0.2 }
move_backward = { keycode = ["s", "down" ], axis    = "lefty",  deadzone = 0.2 }
move_left     = { keycode = ["a", "left" ], axis    = "leftx",  deadzone = 0.2 }
move_right    = { keycode = ["d", "right"], axis    = "leftx",  deadzone = 0.2 }
move_up       = { keycode = "q",            axis    = "righty", deadzone = 0.2 }
move_down     = { keycode = "e",            axis    = "righty", deadzone = 0.2 }
jump          = { keycode = "space",        gamepad = "south"                  }
shoot         = { mouse   = "left",         axis    = "righttrigger"           }
