function (enable_lto target)
	if (CMAKE_BUILD_TYPE STREQUAL "Release")
		include(CheckIPOSupported)
		check_ipo_supported(RESULT ipo_supported OUTPUT ipo_error)
		if (ipo_supported)
			set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
			message(STATUS "LTO enabled")
		else ()
			message(WARNING "LTO error: ${ipo_error}")
		endif ()
	endif ()
endfunction ()
